spring.application.name=backend

# Supabase PostgreSQL Connection
# Added sslmode=require which is necessary for Supabase
spring.datasource.url=jdbc:postgresql://db.rmdkxxfgqjyedhwnnned.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Zinngle@123

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Agora Settings
agora.app-id=${AGORA_APP_ID}
agora.app-certificate=63e8e41cf3ed4b5599068147e229cd1a

# Twilio Settings
twilio.account-sid=VA95bfac0818059af965d1c1ae4fc4945d
twilio.auth-token=19ee2b4dc7584d4e7188706e1ba2c4b3
twilio.phone-number=+91 72184 97496

# Razorpay Settings
razorpay.key-id=rzp_test_Rb7drR7cAxtelX
razorpay.key-secret=JIjiwZXNuF7pUAtAYcK6142t

# Firebase Settings
firebase.private-key-id=608f747df5a718029546b0ffceaf6208d76f38bd
firebase.private-key=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCeZE9hhpn16ROX\nzW39nFHV+0pejl0A0rEPyAQb6jVaHAfOi1glpewWA2G6uWZntTnUcH/9PzN//10l\n4Os5VGgAFjnnKfxmLzECrDuXbwTW/Yw2LMto1alcaYLeAIzBEhGRLffslgcLA3bk\nYge6axu5Afe7LAPW4WtF/7321CGDfqvlMQUOZ0RTDvTSSt9o8jQHN91cMlla78Mi\nbFA1lgC/a3zyBltuyRO7CPEkoQZ7FmzyV+vnuBorQczk0TeGVoOx0ASMXfo9tuqP\naSajFKpvVy458hdOSZBrJsRhWwq6urPpf0KXuV5vui1YMwXecx4ezhH6FwUNGPnW\nsJjKEyRDAgMBAAECggEANMiY65c/l4Ok0+HR1cJSQ00K65flxnBwMSImvGbAgNb2\ngw5Mwb8ZffyChQdj6Qurye/ztyFouC8Ri534xZIrVlwRz8deJW90lb9v3HdS1ZKJ\nN0SWRMlvNyyyP+lO/shWslrvVBhrIHB3HoTMroMjKfRN6kIwxVs5tIoVdDwdLwRw\nuAWliOc708aFAaRnBQozJCWxRMezPdzBKba1Lpl+qeDomvl2AbQToBZbxSYJxhBf\nLzZl5SuNnxDs54KlR66KFwONk+crZEHirey/AQkyXsehXAHJlJKaKvdQdlViNujW\nEBisHROHhElhDjAxEeeCJgjH/jSDK5EQe2e/ZhvEAQKBgQDfM/fL2oyDKSOG2FdU\n3PuEOVfaI1GsOwgwu+v4tE5SifLhqUuTd1WRebBVChcs0sbNvocHMDnyFleZdLBY\nLgl1T5sF3lx3N2xb67O07I3e4wJADaXJCiRZc6aJSph2DcTA3GenKZMWpBpFiqx6\nEHZJywrjSS7w3FqHj4tkTVMPoQKBgQC1qmWzT9Yyr/zEtuMfiPLXBUj5iNrEsLCh\n5BCT1SDj/rZ3sts3DOaZdk333cCgUGuxNjBLWzQLEz50yuflabKva5ynYi6H9FGa\nRQE/qg1pvkoNE1FN0Ql5Aux/khjAatCpzbdwyj0bcWeUQZoPP+o3AU09PNtPRDL1\nae6wqvF5YwKBgH4cmcTHjh7JjrYw5F8hoMbbs4Sf8hSTIhSPCUvzbFF8egwAoKAI\njANvMy9JTUDZMtSq8xYfrI3ZC9O7t6uLD3MF8HxHYA1H9mSVb2spQRuPPgU88M//\nd/xGuPDXgf8p1mJ15ebwOZhQTju+l6c8R+l33IYBIpGan1f6xfJ9MhIhAoGARTt7\nJqr2ZrrLCezpAcufQHKzLOYK+YqcxhW0e6JttnYL8/IluQUhnLqJXD0WfAIqCI8u\nOIm5e78JvljVp4hwoInSWbgBI67oqnJB15FnKzVp4zHJem5/va5vku6KoEoU26Ga\nl1F7mEnPv6CApe8lw3CrjvryWXMUOJL2dD2xaSECgYEAhhm9kx4L2kULxNHW14xL\nRhJvcOsg1zgD1Ac9ujaEvylHvFEvzUfaMPWlmMd4EldXFPc9DaiQTqCyXIv1VC/u\neSTQ9ItXCXwN/PqTqA/vhYrCDHOVQIh7rXXddb5neivYyDdF7HKH/k9aeRGjmEue\n4hQl0Lc97emtzeNsl2ORCLg=\n-----END PRIVATE KEY-----\n
firebase.client-email=firebase-adminsdk-fbsvc@zinngle-73d8e.iam.gserviceaccount.com
firebase.project-id=zinngle-73d8e
firebase.client-id=101109488869786931761
firebase.auth-uri=https://accounts.google.com/o/oauth2/auth
firebase.token-uri=https://oauth2.googleapis.com/token
firebase.auth-provider-x509-cert-url=https://www.googleapis.com/oauth2/v1/certs
firebase.client-x509-cert-url=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40zinngle-73d8e.iam.gserviceaccount.com
firebase.universe-domain=googleapis.com

admin.dashboard.link=https://lovable.dev/projects/e431183f-099e-4fb2-bcf3-dd0407ec4285
